spring.application.name=assignment-9-spring-data-jpa-actuator
spring.datasource.url = jdbc:mysql://localhost:3306/studentdb
spring.datasource.username=root
spring.datasource.password=

spring.jpa.hibernate.ddl-auto = update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

management.endpoints.web.exposure.include=*
debug=true